# Copyright 2021 The Autoware Contributors
# SPDX-License-Identifier: Apache-2.0

- name: Get dash-case name of rmw_implementation
  ansible.builtin.shell: bash -c 'sed -e "s/_/-/g" <<< $(echo {{ rmw_implementation }})'
  register: dash_case_rmw_implementation
  changed_when: false

- name: Install ros-{{ ros_distro }}-{{ dash_case_rmw_implementation.stdout }}
  become: true
  ansible.builtin.apt:
    name: ros-{{ ros_distro }}-{{ dash_case_rmw_implementation.stdout }}
    state: latest
    update_cache: true

- name: Add RMW_IMPLEMENTATION to .bashrc
  ansible.builtin.lineinfile:
    dest: ~/.bashrc
    line: export RMW_IMPLEMENTATION={{ rmw_implementation }}
    state: present
    create: true
    mode: 0644
