---
- name: Build Autoware Vehicle Dependencies
  hosts: localhost
  connection: local
  vars:
    rosdep_install_dependency_types:
      - buildtool
      - buildtool_export
      - build_export
      - build

  roles:
    - role: bounverif.ros.ros2_install
    - role: bouncmpe.autoware_vehicle.ros_requirements_install
    - role: bounverif.ros.cuda_toolkit_install
    - role: bounverif.ros.repositories
    - role: bounverif.ros.file_operations
    - role: bounverif.ros.rosdep_install
