# General Vars
ros_workspace: /tmp/autoware-istanbul/ros/autoware_universe
ros_source_dir:  "{{ ros_workspace }}/src"
ros_build_dir: "{{ ros_source_dir }}/build"
ros_install_dir: "/opt/bouncmpe/{{ ros_distro }}"

# Requirement role vars
ros_distro: humble
ros_distro_type: desktop
collection_name: autoware_universe
rmw_implementation: rmw_cyclonedds_cpp
base_image: ubuntu:22.04
cuda_base_image: ubuntu:22.04
prebuilt_base_image: ubuntu:22.04
cuda_version: 11.6
cudnn_version: 8.4.1.50-1+cuda11.6
tensorrt_version: 8.4.2-1+cuda11.6
clang_format_version: 16.0.0

# Rosdep role
rosdep_install_init: true

repositories_download_dir: "{{ ros_source_dir }}"

repositories:
  - {
    url: https://github.com/autowarefoundation/autoware.universe.git,
    dest: "{{ repositories_download_dir }}/{{ collection_name }}/",
    version: main
  }
  # Core
  - {
    url: https://github.com/autowarefoundation/autoware_msgs.git,
    dest: "{{ repositories_download_dir }}/{{ collection_name }}/autoware_msgs",
    version: main
  }
  - {
    url: https://github.com/autowarefoundation/autoware_adapi_msgs.git,
    dest: "{{ repositories_download_dir }}/{{ collection_name }}/autoware_adapi_msgs",
    version: main
  }
  - {
    url: https://github.com/autowarefoundation/autoware_common.git,
    dest: "{{ repositories_download_dir }}/{{ collection_name }}/autoware_common",
    version: main
  }
  - {
    url: https://github.com/autowarefoundation/autoware.core.git,
    dest: "{{ repositories_download_dir }}/{{ collection_name }}/autoware.core",
    version: main
  }
  - {
    url: https://github.com/tier4/autoware_auto_msgs.git,
    dest: "{{ repositories_download_dir }}/{{ collection_name }}/external/autoware_auto_msgs",
    version: tier4/main
  }
  # Universe
  - {
    url: https://github.com/tier4/tier4_ad_api_adaptor.git,
    dest: "{{ repositories_download_dir }}/{{ collection_name }}/external/tier4_ad_api_adaptor",
    version: tier4/universe
  }
  - {
    url: https://github.com/tier4/tier4_autoware_msgs.git,
    dest: "{{ repositories_download_dir }}/{{ collection_name }}/external/tier4_autoware_msgs",
    version: tier4/universe
  }
  - {
    url: https://github.com/MORAI-Autonomous/MORAI-ROS2_morai_msgs.git,
    dest: "{{ repositories_download_dir }}/{{ collection_name }}/external/morai_msgs",
    version: main
  }
  - {
    url: https://github.com/tier4/muSSP.git,
    dest: "{{ repositories_download_dir }}/{{ collection_name }}/external/muSSP",
    version: tier4/main
  }
  - {
    url: https://github.com/tier4/ndt_omp.git,
    dest: "{{ repositories_download_dir }}/{{ collection_name }}/external/ndt_omp",
    version: tier4/main
  }
  - {
    url: https://github.com/tier4/pointcloud_to_laserscan.git,
    dest: "{{ repositories_download_dir }}/{{ collection_name }}/external/pointcloud_to_laserscan",
    version: tier4/main
  }
  - {
    url: https://github.com/MapIV/eagleye.git,
    dest: "{{ repositories_download_dir }}/{{ collection_name }}/external/eagleye",
    version: autoware-main
  }
  - {
    url: https://github.com/MapIV/rtklib_ros_bridge.git,
    dest: "{{ repositories_download_dir }}/{{ collection_name }}/external/rtklib_ros_bridge",
    version: ros2-v0.1.0
  }
  - {
    url: https://github.com/MapIV/llh_converter.git,
    dest: "{{ repositories_download_dir }}/{{ collection_name }}/external/llh_converter",
    version: ros2
  }
